export const PUB_SUB_EVENTS = {
  BID_ADDED: 'BID_ADDED',
  NOTIFICATION_ADDED: 'NOTIFICATION_ADDED',
  AUCTION_STATUS_CHANGED: 'AUCTION_STATUS_CHANGED',
  MESSAGE_SENT: 'MESSAGE_SENT',
  MESSAGE_UPDATED: 'MESSAGE_UPDATED',
  CHAT_READ_STATUS_UPDATED: 'CHAT_READ_STATUS_UPDATED',
} as const;
