export const PUB_SUB_EVENTS = {
  AUCTION_CREATED: 'AUCTION_CREATED',
  BID_ADDED: 'BID_ADDED',
  NOTIFICATION_ADDED: 'NOTIFICATION_ADDED',
  AUCTION_STATUS_CHANGED: 'AUCTION_STATUS_CHANGED',
  MESSAGE_SENT: 'MESSAGE_SENT',
  MESSAGE_UPDATED: 'MESSAGE_UPDATED',
  CHAT_READ_STATUS_UPDATED: 'CHAT_READ_STATUS_UPDATED',
  WALLET_UPDATED: 'WALLET_UPDATED',
  WITHDRAWAL_REQUESTED: 'WITHDRAWAL_REQUESTED',
  WITHDRAWAL_STATUS_CHANGED: 'WITHDRAWAL_STATUS_CHANGED',
  ESCROW_STATUS_CHANGED: 'ESCROW_STATUS_CHANGED',
  DISPUTE_STATUS_CHANGED: 'DISPUTE_STATUS_CHANGED',
};
