import { registerEnumType } from '@nestjs/graphql';

export enum InAppNotificationType {
  OUTBID = 'OUTBID',
  AUCTION_WON = 'AUCTION_WON',
  AUCTION_ENDED_SELLER = 'AUCTION_ENDED_SELLER',
  DEPOSIT_SUCCESSFUL = 'DEPOSIT_SUCCESSFUL',
  WITHDRAWAL_COMPLETED = 'WITHDRAWAL_COMPLETED',
  AUCTION_STARTED = 'AUCTION_STARTED',
  WELCOME = 'WELCOME',
  NEW_BID = 'NEW_BID',
  AUCTION_CANCELLED = 'AUCTION_CANCELLED',
  AUCTION_CANCELLED_BY_ADMIN = 'AUCTION_CANCELLED_BY_ADMIN',
  NEW_CHAT_MESSAGE = 'NEW_CHAT_MESSAGE',
  REVIEW_RECEIVED = 'REVIEW_RECEIVED',
  REVIEW_REPLIED = 'REVIEW_REPLIED',
  AUTO_BID_PLACED = 'AUTO_BID_PLACED',
  AUTO_BID_EXHAUSTED = 'AUTO_BID_EXHAUSTED',
}

registerEnumType(InAppNotificationType, {
  name: 'InAppNotificationType',
});
